version: '3.9'
services:
  api1:
    build:
      context: .
      dockerfile: "SearchAPI/Dockerfile"
    ports:
      - 9001:80
    volumes:
      - C:/work/developmen of large systems/db:/data
  api2:
    build:
      context: .
      dockerfile: "SearchAPI/Dockerfile"
    ports:
      - 9002:80
    volumes:
      - C:/work/developmen of large systems/db:/data
  web:
    build:
      context: .
      dockerfile: "WebSearch/Dockerfile"
    ports:
      - 9003:80
